<?php

/**
 * Implementation of hook_module_implements_alter(&$implementations, $hook)
 *
 * Disables panopoly_images from calling media_wysiwyg_allowed_view_modes_alter
 * which sets confusing names on the various selections involved
 *
 * Panopoly rules!
 */
function reset_panopoly_media_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'media_wysiwyg_allowed_view_modes_alter') {
    unset($implementations['panopoly_images']);
  }
}