<?php

/**
 * @file
 * An installation file for Panopoly Widgets
 */

/**
 * Implementation of hook_install().
 */
function ucsf_pharmacy_panels_entities_install() {
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/vegetables-demo-image.png', 'vegetables-demo-image.png', 'image');
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/vegetables_demo_spotlight.jpeg', 'vegetables_demo_spotlight.jpeg', 'spotlight');
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/preview-file.txt', 'preview-file.txt', 'basic_file');
  ucsf_pharmacy_panels_entities_save_default_video_data();
}

/**
 * Implementation of hook_uninstall().
 */
function ucsf_pharmacy_panels_entities_uninstall() {

}

/**
 * Implementation of hook_field_schema().
 */
function ucsf_pharmacy_panels_entities_field_schema($field) {
  if ($field['type'] == 'panopoly_spotlight') {
    $schema['columns']['title'] = array(
      'type' => 'varchar',
      'length' => '255',
      'not null' => FALSE,
    );

    $schema['columns']['description'] = array(
      'type' => 'text',
      'size' => 'big',
      'not null' => FALSE,
    );

    $schema['columns']['fid'] = array(
      'type' => 'int', 
      'not null' => FALSE,
      'unsigned' => TRUE,
    );

    $schema['columns']['link'] = array(
      'type' => 'varchar',
      'length' => '255',
      'not null' => FALSE,
    );

    $schema['indexes'] = array(
      'fid' => array('fid'),
    );

    $schema['foreign keys'] = array(
      'fid' => array(
        'table' => 'file_managed',
        'columns' => array('fid' => 'fid'),
      ),
    );

    return $schema;
  }
}

/**
 * Implementation of hook_update_N().
 */
function ucsf_pharmacy_panels_entities_update_7001(&$sandbox) {
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/vegetables-demo-image.png', 'vegetables-demo-image.png', 'image');
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/vegetables_demo_spotlight.jpeg', 'vegetables_demo_spotlight.jpeg', 'spotlight');
  ucsf_pharmacy_panels_entities_save_default_file_data(drupal_get_path('module', 'ucsf_pharmacy_panels_entities') . '/default_content/preview-file.txt', 'preview-file.txt', 'basic_file');
  ucsf_pharmacy_panels_entities_save_default_video_data();
}

/**
 * Implementation of hook_update_N().
 *
 * Revert panopoly_widget fields to avoid data loss in update 7003.
 */
function ucsf_pharmacy_panels_entities_update_7002(&$sandbox) {
  module_load_include('inc', 'features', 'features.export');
  features_include();
  features_revert(array('ucsf_pharmacy_panels_entities' => array('field')));
}

/**
 * Implementation of hook_update_N().
 *
 * Move video mediafield data into a file field.
 */
function ucsf_pharmacy_panels_entities_update_7003(&$sandbox) {

  $results = entity_load('fieldable_panels_pane');
  foreach ($results as $entity) {

    foreach ($entity->field_video_video[LANGUAGE_NONE] as $f) {
      $entity->field_video_file[LANGUAGE_NONE][] = array(
        'fid' => $f['fid'],
        'display' => 1,
      );
    }

    $form_state['entity'] = $entity;
    $form_state['values'] = (array) $entity;
    $form_state['values']['link'] = ($form_state['values']['link'] == 0) ? NULL : $form_state['values']['link'];
    $form_state['values']['reusable'] = ($$form_state['values']['reusable'] == 0) ? NULL : $form_state['values']['reusable'];
    drupal_form_submit('fieldable_panels_panes_entity_edit_form', $form_state);
  }
  field_delete_field('field_video_video');
}

/**
 * Implements hook_update_N().
 *
 * Convert panel panes with "uuid" style subtypes into "fpid" style subtypes.
 */
function ucsf_pharmacy_panels_entities_update_7004(&$sandbox) {

  $results = db_select('panels_pane', 'p')
    ->fields('p', array('pid', 'subtype'))
    ->execute()
    ->fetchAll();

  foreach ($results as $result) {
    if (substr($result->subtype, 0, 5) == 'uuid:') {
      $uuid = substr($result->subtype, 5);

      $fpid = db_select('fieldable_panels_panes', 'fpp')
        ->fields('fpp', array('fpid'))
        ->condition('uuid', $uuid)
        ->execute()
        ->fetchField();

      if (!empty($fpid)) {
        $subtype = "fpid:" . $fpid;

        db_update('panels_pane')
        ->fields(array('subtype' => $subtype))
        ->condition('pid', $result->pid)
        ->execute();
      }
    }
  }
}

/**
 * Helper function to save default file data.
 */
function ucsf_pharmacy_panels_entities_save_default_file_data($filepath, $filename, $type) {
  $fid = variable_get('ucsf_pharmacy_panels_entities_default_' . $type . '_fid', NULL);
  if (empty($fid)) {
    $file = fopen($filepath, 'r');
    $file_raw = fread($file, filesize($filepath));
    $file_entity = file_save_data($file_raw, 'public://' . $filename);

    if (!empty($file_entity->fid)) {
      variable_set('ucsf_pharmacy_panels_entities_default_' . $type . '_fid', $file_entity->fid);

      return $file_entity->fid;
    }
  }
}

/**
 * Helper function to save default video data.
 */
function ucsf_pharmacy_panels_entities_save_default_video_data() {
  $fid = variable_get('ucsf_pharmacy_panels_entities_default_video_fid', NULL);

  if (empty($fid)) {

    // Create the file object
    $file = (object) array(
      'uid' => 1,
      'filename' => 'The Drupal Song Music Video',
      'uri' => 'youtube://v/lZ-s3DRZJKY',
      'filemime' => 'video/youtube',
      'status' => 1,
      'type' => 'video',
      'filesize' => 0,
      'timestamp' => REQUEST_TIME,
    );

    // Save the file object
    module_invoke_all('file_presave', $file);
    module_invoke_all('entity_presave', $file, 'file');
    drupal_write_record('file_managed', $file);
    module_invoke_all('file_insert', $file);
    module_invoke_all('entity_insert', $file, 'file');

    // Record the result
    if (!empty($file->fid)) {
      variable_set('ucsf_pharmacy_panels_entities_default_video_fid', $file->fid);
    }
  }
}

