<?php

include_once('ucsf_pharmacy_pages.features.inc');

/**
 * Implementation of drupal_alter() to update menu block settings in 
 * case of IPE callback magic
 */
function ucsf_pharmacy_pages_menu_block_tree_alter($tree, $config) {
  if (arg(0) == 'panels' && arg(1) == 'ajax') {
    // Set the active trail for all main menu items. This will work
    // for our demo, but might break with more complicated menus. 
    // By might, of course, we mean likely will. Sigh double sigh. 
    // It all gets fixed by refresh of the page though....
    foreach($tree as $key => $value) {
      $tree[$key]['link']['in_active_trail'] = TRUE;
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter
 * 
 * If more content types implment chunks, should switch to a generic form alter 
 * checking $form_id and $form['#node_edit_form']
 */
function ucsf_pharmacy_pages_form_panopoly_page_node_form_alter(&$form, &$form_state, $form_id) {

  if(!empty($form['field_panels_chunks']['und'])){
    //load the css just for the form that hides weight abilities
    drupal_add_css(drupal_get_path('module', 'ucsf_pharmacy_pages') . '/ucsf_pharmacy_pages_edit_form.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));

    //add a 'Chunk #' label to each chunk
    foreach($form['field_panels_chunks']['und'] as $index => $chunk) {
  	  if (is_numeric($index)){
        $form['field_panels_chunks']['und'][$index]['#title'] = t('Chunk @index', array('@index' => $index));	
  	  }
  	}
    //if the chunk data exists
    if (!empty($form['field_panels_chunks']['und'][0]['#default_value'])){
      //expand the chunks fieldgroup
      $form['#groups']['group_panels_chunks']->format_settings['formatter'] = 'collapsible';
    }
  }
  //dpm($form);
}
