<?php
/**
 * @file
 * Code for the UCSF Pharmacy Syndicated People feature.
 */
//main url is defined in ucsf_pharmacy_central_taxonomy
include_once 'ucsf_pharmacy_syndicated_people.features.inc';

define('UCSF_PHARMACY_SYNDICATED_PEOPLE_PATH','feed/people-');

/**
 * Implements hook_form_FORM_ID_alter
 */
function ucsf_pharmacy_syndicated_people_form_feeds_import_form_alter(&$form,$form_state,$form_id) {

	//if it is the form for people syndication, automate some things
	if ($form['#importer_id'] == 'syndicated_people') {
		//set tid filter to empty string
        $filter = 'all';
        //comment or remove this to stop the tid filter
        if(variable_get('ucsf_pharmacy_edu_code',false)){
			//$filter = 'edu?edu_tid=' . $site;
			$filter = 'edu';
		}
		$form['feeds']['FeedsHTTPFetcherTimestamp']['source']['#default_value'] = UCSF_PHARMACY_MAIN_URL . UCSF_PHARMACY_SYNDICATED_PEOPLE_PATH . $filter;

		//disable the field, because "no touchy!"
		$form['feeds']['FeedsHTTPFetcherTimestamp']['source']['#disabled'] = TRUE;
	}
}