<?php

function ucsf_pharmacy_webedit_ucsf_webedit_format_replace_alter(&$replaceformats) {
  //override the following with webedit:

  //from pharmacy panels sites
  $replaceformats[]='panopoly_wysiwyg_text';
  //$replaceformats[]='panopoly_html_text';

  //from starterkit/microsites
  //$replaceformats[]='html_all';
  $replaceformats[]='advanced_wysiwyg';
  $replaceformats[]='simple_wysiwyg';
  //$replaceformats[]='comments';
  //$replaceformats[]='full_html';

  //other
  //$replaceformats[]='ds_code';
  //$replaceformats[]='plain_text';

}

/**
 * 
 * 2014.0102 frankfarm (via ericdavila)
 * 2014.0124 frankfarm added paddingbottomnone to handle the case of the main image at https://preview-clinicalpharmacy.ucsf.edu/research
 * date unknown frankfarm added fine print
 * 2014.0404 frankfarm added center
 * 
 * this adds our custom styles to the style dropdown menu in CKeditor.
 * 
*/
function ucsf_pharmacy_webedit_ucsf_webedit_stylesset_alter(&$stylesset) {
  $stylesset[]= array('name' => 'Emphatic','element' => 'p','attributes' => array('class' => 'emphatic'));
  $stylesset[]= array('name' => 'Eyecatching','element' => 'p','attributes' => array('class' => 'eyecatching'));
  $stylesset[]= array('name' => 'Featured','element' => 'p','attributes' => array('class' => 'featured'));
  $stylesset[]= array('name' => 'Fine print','element' => 'p','attributes' => array('class' => 'fine-print'));
  $stylesset[]= array('name' => 'No padding below floated image','element' => 'p','attributes' => array('class' => 'paddingbottomnone'));
  //trying for later inclusion in ucsf_webedit
  $stylesset[]= array('name' => 'li clearfix','element' => 'li','attributes' => array('class' => 'webedit-clearfix'));

}
/*
// admin-only styles, see pharmd.ucsf.edu/curriculum/outcomes for an example
showhidetoggle
hideonpageload
*/

/**
 * Alter/add to the list of Drupal role permissions tied directly to WebEdit
 *
 * $webedit_perm_match permissions will match the WebEdit text format EXACTLY
 *
 * $webedit_perm_on permissions are "soft on"
 * (role on if allowed to use webedit, otherwise unchanged)
 *
 */
function ucsf_pharmacy_webedit_ucsf_webedit_permissions_alter(&$webedit_perm_match,&$webedit_perm_on) {
  $webedit_perm_match[] = 'view the administration theme';
}

/**
 * Implementation of hook_init()
 */
function ucsf_pharmacy_webedit_init() {

  // Adding the webedit css file to the theme so it will show up in the WYSIWYG
  drupal_add_css( drupal_get_path( 'module', 'ucsf_pharmacy_webedit') . '/ucsf_pharmacy_webedit.css',
    array(
      'group' => CSS_THEME
      ,'every_page' => TRUE
      ,'weight' => -1
    )
  );
}
/**
 * implements hook_wysiwyg_editor_settings_alter
 */
function ucsf_pharmacy_webedit_wysiwyg_editor_settings_alter(&$settings, $context) {
  // The $context variable contains information about the wysiwyg profile we're using
  // In this case we just need to check that the editor being used is ckeditor
 
  if ($context['profile']->format == 'webedit' && $context['profile']->editor == 'ckeditor') {
 
    // The $settings variable contains all the config options ckeditor uses. 
    // The array keys correspond directly with any setting that can be applied 
    // to CKEditor - as outlined in the CKEditor docs: 
    // http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html 
    // Another way to override configuration is to use your own configuration javascript
    // file. In this case, we're going to add our own configuration file that will
    //$settings['webeditConfig'] = base_path() . drupal_get_path('module', 'ucsf_webedit') . '/ucsf_webedit_config.js';
    $settings['customConfig'] = base_path() . drupal_get_path('module', 'ucsf_pharmacy_webedit') . '/ucsf_pharmacy_webedit_config.js';

  }
  //end ckeditor 'if'
}
/**
 * implements hook_module_implements_alter
 */
function ucsf_pharmacy_webedit_module_implements_alter(&$implementations, $hook){
  //drop ucsf_pharmacy_webedit to end of list so it
  //executes after webedit 
  //(see previous hook in this file)
  if ($hook == 'wysiwyg_editor_settings_alter') {
    unset($implementations['ucsf_pharmacy_webedit']);
    $implementations['ucsf_pharmacy_webedit'] = FALSE;
  }
}
